# Generated by Django 5.1.2 on 2024-11-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='id_user',
            new_name='user',
        ),
    ]
